## library() calls go here
library(conflicted)
library(dotenv)
options(future.fork.enable = TRUE)
library(targets)
library(tarchetypes)
library(FTMS.peakCharacterization)
library(methods)
disable_logging()
show_progress()
library(furrr)
future::plan(multicore)
FTMS.peakCharacterization::set_internal_map(furrr::future_map)
library(rprojroot)
library(ggplot2)
theme_set(cowplot::theme_cowplot())
library(patchwork)
library(ggridges)
library(dplyr)
library(glue)
library(here)
library(tidyr)
options(future.globals.maxSize = 2000 * 1024^2)
library(rmarkdown)
library(documentNumbering)
tar_option_set(memory = "transient")
